name: chat_app_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_database: ^10.0.9
  equatable: ^2.0.5
  easy_localization: ^3.0.1
  google_fonts: ^3.0.1
  path_provider: ^2.0.11
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  get_it: ^7.2.0
  firebase_core: ^2.4.1
  shared_preferences: ^2.0.16
  timeago: ^3.3.0
  jiffy: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/


  fonts:
    - family: EloquiaText
      fonts:
        - asset: assets/fonts/EloquiaText.ttf
